"""Init

Revision ID: 8088bab935e3
Revises: 
Create Date: 2023-04-18 12:46:05.213028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8088bab935e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_birth_date'), 'contact', ['birth_date'], unique=False)
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_contact_first_name'), 'contact', ['first_name'], unique=False)
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_index(op.f('ix_contact_last_name'), 'contact', ['last_name'], unique=False)
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_last_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_first_name'), table_name='contact')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_index(op.f('ix_contact_birth_date'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
